### ISSUE TITLE
We need change give-author address

### ISSUE THREAD

**Issue by poiuty** [dashpay/p2pool-dash#13]
Let`s change give-author address to DASH software development donations address.
XpAy7r5RVdGLnnjWNKuB9EUDiJ5Tje9GZ8

Find this code https://github.com/dashpay/p2pool-dash/blob/master/p2pool/data.py#L52
```
DONATION_SCRIPT = '41042d71f6448f92c35ede838e3922313b162cbf20d357e7d067115aac8d1a27f66a89b46dee086775c8b083ee5f06fe1c08d1d0ae0668d029aed17e1f8eaea544d4ac'.decode('hex')
```

**Comment by poiuty** [comment]
https://github.com/ntkrnl/yacoin-p2pool/blob/master/test.py
http://bitcoin.stackexchange.com/questions/12365/how-to-change-donation-address-of-p2pool

**Comment by poiuty** [comment]
Find decode. Now donate send to https://chainz.cryptoid.info/dash/address.dws?Xcfme7cJDpWBgQE7Bsf71pPmse9YCjV2CF.htm
```
darkcoind decodescript '41042d71f6448f92c35ede838e3922313b162cbf20d357e7d067115aac8d1a27f66a89b46dee086775c8b083ee5f06fe1c08d1d0ae0668d029aed17e1f8eaea544d4ac'
{
    "asm" : "042d71f6448f92c35ede838e3922313b162cbf20d357e7d067115aac8d1a27f66a89b46dee086775c8b083ee5f06fe1c08d1d0ae0668d029aed17e1f8eaea544d4 OP_CHECKSIG",
    "reqSigs" : 1,
    "type" : "pubkey",
    "addresses" : [
        "Xcfme7cJDpWBgQE7Bsf71pPmse9YCjV2CF"
    ],
    "p2sh" : "7i3t8jUJ7i2UAmqTs6PMvN8S3kofVUbrbg"
}
```

**Comment by poiuty** [comment]
Can`t generate uncompress public key. Only compress.
```
from p2pool.dash import data, networks, sha256
from p2pool.util import pack

print data.pubkey_hash_to_script2(data.address_to_pubkey_hash('XpAy7r5RVdGLnnjWNKuB9EUDiJ5Tje9GZ8', networks.nets['dash'])).encode('hex') #76a91493eb5d3f266f2e0cd2468caffa5f6a933b2c0b8588ac
#darkcoind decodescript '76a91493eb5d3f266f2e0cd2468caffa5f6a933b2c0b8588ac'
#{
#    "asm" : "OP_DUP OP_HASH160 93eb5d3f266f2e0cd2468caffa5f6a933b2c0b85 OP_EQUALVERIFY OP_CHECKSIG",
#    "reqSigs" : 1,
#    "type" : "pubkeyhash",
#    "addresses" : [
#        "XpAy7r5RVdGLnnjWNKuB9EUDiJ5Tje9GZ8"
#    ],
#    "p2sh" : "7if3tTT8rexwn1hP1JFCf1FefjermWPngY"
#}
```

Also I find
https://github.com/Neisklar/p2pool-quarkcoin/blob/master/p2pool/data.py#L56-L66
https://bitcointalk.org/index.php?topic=18313.msg10613795#msg10613795

**Comment by thelazier** [comment]
So, only owner (who has private key) of address "XpAy7r5RVdGLnnjWNKuB9EUDiJ5Tje9GZ8" can get this pubkey from "validateaddress" command with "iscompressed" : false  then we can wrap this pubkey with OP_CHECKSIG and put into DONATION_SCRIPT string.

**Comment by poiuty** [comment]
https://dashtalk.org/threads/p2pool-repository-and-python-modules.3380/page-8#post-51590

**Comment by poiuty** [comment]
Also we need fix this too
https://github.com/dashpay/p2pool-dash/blob/master/p2pool/dash/data.py#L13-L16
