### ISSUE TITLE
p2pool Solo

### ISSUE THREAD

**Issue by RommieATIKA** [dashpay/p2pool-dash#45]
How to convert p2pol to solomaining?

**Comment by schinzelh** [comment]
I'd recommend setting up your own pool, e.g. UNOMP --> https://github.com/UNOMP/unified-node-open-mining-portal

Just follow the readme, the installation is straight forward.

**Comment by RommieATIKA** [comment]
This is beta software. All of the following are things that can change and break an existing setup: functionality of any feature, structure of configuration files and structure of redis data. 
I need to translate the working p2pol into solo, but how?

**Comment by ilsawa** [comment]
p2pool is not intended for solo mining. Use NOMP.
In addition, at present this p2pool is not able to find blocks and only finds orphans https://github.com/dashpay/p2pool-dash/issues/43

**Comment by schinzelh** [comment]
@RommieATIKA Everything related to crypto mining is beta software. UNOMP is well known and stable pool software. If you need help setting up your own pool write me an email: holger@dash.org

**Comment by RommieATIKA** [comment]
I did not notice, I have everything ok, only it is necessary to isolate or solo.

**Comment by schinzelh** [comment]
There is no "solo" mining option in Dash anymore, the API/RPC for mining in dashd has been removed years ago. The only way to properly "solo" mine now is to setup your own private pool.

**Comment by RommieATIKA** [comment]
You do not have your own customized pool under DASH

**Comment by RommieATIKA** [comment]
No I do not install it. Can you know, or do you have your project under DASH?

**Comment by schinzelh** [comment]
All Dash specific changes were merged to upstream, no Dash customized pool software needed.

**Comment by RommieATIKA** [comment]
I need a solo mode.

**Comment by schinzelh** [comment]
I repeat: Dash does not have a solo mode anymore, the only way to mine Dash is

a) p2pool or
b) private pool (e.g. UNOMP)

If both of these options are not feasable, you'll need to use public pools like coinmine.pl or suprnova.cc

**Comment by RommieATIKA** [comment]
Will you be able to configure the output of UNOMP under DASH?

**Comment by schinzelh** [comment]
You can send all coins mined on your UNOMP to your own Dash address, yes.

If you like i can set up a VPS/UNOMP for you, and if you like what you see you can rent it for a monthly fee.

**Comment by RommieATIKA** [comment]
I'll buy it if I like it, I do not have to worry about not registering anything, just to collect the blocks and make payments.

**Comment by gery6** [comment]
If you don't want to install your own instance. You can try to use https://www.cupa.co for mining.
Good luck. This pool works with other currencies based on X11. But not the Digital Coin (DGC).
Payments are working fine for cream coin there. Dash is also supported there, but nobody mines it. 
Good luck.

**Comment by Bdydy** [comment]
@schinzelh 
Hi schinzelh, I need some help for build an private X11 pool.
Regards

**Comment by schinzelh** [comment]
@Bdydy please contact me via email: holger@dashdot.io

**Comment by Bdydy** [comment]
@schinzelh 
Email sent!

**Comment by farsider350** [comment]
You can use p2pool for solo mining, just change the suffix and prefix to your own and set persist to false.

**Comment by kr1z1s** [comment]
> You can use p2pool for solo mining, just change the identifier and prefix to your own and set persist to false. Found in networks/dash.py

Are you stupid? p2pool was not created for solo. It's a distributed network. Dash network is very large. There is no point in creating a solo node. On the contrary, it is necessary to increase Hasrat network п2пула. Don't write nonsense.

**Comment by farsider350** [comment]
Whether or not you like it, doesn't change the fact that it can be done and happens on a daily basis with many coins. Do you need proof or are you just being a complete lost soul by calling people stupid that know for a fact that it is possible to do?

**Comment by kr1z1s** [comment]
> Whether or not you like it, doesn't change the fact that it can be done and happens on a daily basis with many coins. Do you need proof or are you just being a complete lost soul by calling people stupid that know for a fact that it is possible to do?

You're a fool because you don't understand. Solo nodes kill p2pool.

Being able to do solos was a mistake. And if you don't understand that, then you're a random person here. P2pool's the network. No solo nodes should be.

In dash p2pool - Expected time to block (pool): | 1d 2h 31m 26s

This is a very long time. And then there is a stupid kid and learning to create a solo node. You are a pest? Go to your github and put the code you stole from others in it.
-- | --

**Comment by farsider350** [comment]
Open source buddy, and my codes are refined to out do their previous owners (who make their codes private for personal profit gains).

The truth is the truth and it can be done, get your panties out of a twist. End of story.

**Comment by kr1z1s** [comment]
> Open source buddy, and my codes are refined to out do their previous owners (who make their codes private for personal profit gains).
> 
> The truth is the truth and it can be done, get your panties out of a twist. End of story.

There are large coins - BTC, BCH, LTC, DASH. 
If we want independence from large pools, we need to make a NETWORK, not a solo node. If you don't understand, I feel sorry for you.
These coins need a LARGE network, not a solo node.

**Comment by farsider350** [comment]
I completely understand, never said I didn't.

Still doesn't change the fact that it can be done. Quite easily too, change the identifier and prefix to your own and set persist to false. Found in networks/dash.py

Nobody owns p2pool, and any p2pool you think you own was forked from the original source, stop acting like you own the code and can control it and move on.

**Comment by kr1z1s** [comment]
> I completely understand, never said I didn't.
> 
> Still doesn't change the fact that it can be done. Quite easily too, change the identifier and prefix to your own and set persist to false. Found in networks/dash.py
> 
> Nobody owns p2pool, and any p2pool you think you own was forked from the original source, stop acting like you own the code and can control it and move on.

No you don't. If there are no working networks, there will be no development. Forrest didn't just lose interest in the project. There are only a few programmers who can develop this project. Neither you nor I belong to them. So don't disturb them.

**Comment by kr1z1s** [comment]
> I completely understand, never said I didn't.
> 
> Still doesn't change the fact that it can be done. Quite easily too, change the identifier and prefix to your own and set persist to false. Found in networks/dash.py
> 
> Nobody owns p2pool, and any p2pool you think you own was forked from the original source, stop acting like you own the code and can control it and move on.

No need to philosophize about open source. Develop p2pool!

Here the person is engaged in the development of p2pool - https://github.com/jtoomim/p2pool/pull/25

And you are engaged in demagogy, sabotage and only interfere.

**Comment by farsider350** [comment]
I know exactly who Jtoomim is and for your information he has no problem at all wtih people running persist=false for local chains as stated right here https://github.com/jtoomim/p2pool/pull/14

And for your information this repo right here that you are consistently going on and on about crap in has nothing to do with Jtoomims github and I'm 99% sure wasn't originally forked from his project either. It seems like you just have your back up about people not helping your own chains that are run on closed source codes to profit off your own merge mining ventures. http://p2p-spb.xyz:5025/static/

You are pathetic, stealing codes, making a closed group of only a select few pool owners, closing off the source code than battering others for not joining your pools. Absolutely pathetic.

**Comment by UdjinM6** [comment]
P2pool was developed to be one distributed pool but it's an open source software and you can tweak it and use it the way you like, no need to argue about both of these point.

Pls take that drama to twitter, discord or smth if you want to continue.

Closing.
