### ISSUE TITLE
Warning: this version is no longer maintained

### ISSUE THREAD

**Issue by buechling** [dashpay/p2pool-dash#5]
although this seems official..
this version of p2pool for darkcoin will no longer work! 
( http timeout for p2pool port )

a working version can be found here:
https://github.com/vertoe/p2pool-drk

**Comment by poiuty** [comment]
Hi. It`s version now work.
If u create fork and do some fix => u can create pool request for this repo.

**Comment by jakehaas** [comment]
Pull request #10 will make this up to date and working.

**Comment by thelazier** [comment]
PR #24 will possibly make this up to date and working with DashCore v0.12.1.

**Comment by UdjinM6** [comment]
original issue was fixed by #10 , closing
