### ISSUE TITLE
p2pool is downloading shares....

### ISSUE THREAD

**Issue by ourlink** [dashpay/p2pool-dash#62]
We have upgraded to the latest DASHD (v0.13.0) and upgraded our P2Pool Node to run the current p2pool-dash. However, when we start up p2pool-dash we are receiving the following error;
```
Unhandled Error
Traceback (most recent call last):
  File "/root/p2pool-dash/p2pool/main.py", line 718, in run
    reactor.run()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
--- <exception caught here> ---
  File "/root/p2pool-dash/p2pool/dash/stratum.py", line 39, in _send_work
    x, got_response = self.wb.get_work(*self.wb.preprocess_request('' if self.username is None else self.username))
  File "/root/p2pool-dash/p2pool/dash/worker_interface.py", line 129, in get_work
    x, handler = self._inner.get_work(*args)
  File "/root/p2pool-dash/p2pool/work.py", line 265, in get_work
    raise jsonrpc.Error_for_code(-12345)(u'p2pool is downloading shares')
p2pool.util.jsonrpc.NarrowError: -12345 p2pool is downloading shares
```
We have tried to trace this back to see if we can determine the issue but have not had any success.

We have the dashd daemon running and have used ``dash-cli getinfo`` to check that it is running without errors. Executing ``dash-cli getinfo`` returns fine;
```
{
  "version": 130000,
  "protocolversion": 70213,
  "walletversion": 61000,
  "balance": 0.00000000,
  "privatesend_balance": 0.00000000,
  "blocks": 1004393,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 59154989.97378415,
  "testnet": false,
  "keypoololdest": 1486504219,
  "keypoolsize": 1001,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}
```

Any help in what might be the cause?

**Comment by UdjinM6** [comment]
Thanks for reporting. Yes, we had to bump share version to incorporate data required by Coinbase Special Transaction (see https://github.com/dashpay/dips/blob/master/dip-0004.md#coinbase-special-transaction). This means that shares found by "old" version is not compatible with the new ones and you'll have to start fresh. However, since everyone else is running on an "old" version you'd probably want to run it too for now, probably until DIP3 activation at which point everyone running p2pool nodes will have to upgrade to be able to produce correct coinbase/blocks.

**Comment by ourlink** [comment]
Thanks for the quick response. We kind of expected that may be the issue, but we were not sure when the new share version was expected to go into effect. Thought it was with the v0.13.0 release.

We'll monitor for DIP3 activation and upgrade our pools at that time.

**Comment by ourlink** [comment]
We were notified by @Tungfa to go ahead and update our pools because DIP3 had been activated.

We have two of our pools activated but again we are seeing the same issue as before (see previous post with error - downloading shares...). 

The other problem we are seeing is in the web-interface, no statistics are being displayed. Even using the base web interface we get no stats displayed.   see this link - [http://dash06.p2poolmining.us:7903/static/original/](url)

**Comment by tungfa** [comment]
hey guys

i CC Udjin , core dev, he will be up in a couple of hours to ship in 

P

Philipp Engelhorn
Dash Core Group Inc.
tungfa@dash.org
www.dash.org

**Comment by UdjinM6** [comment]
I guess @tungfa is way too excited about v13 😄 

No, DIP3 is NOT activated, you can check it for yourself via rpc:
```
> dash-cli getblockchaininfo | grep -A 11 dip0003
    "dip0003": {
      "status": "started",
      "bit": 3,
      "period": 4032,
      "threshold": 3226,
      "windowStart": 1008000,
      "windowBlocks": 6,
      "windowProgress": 0.001859888406695598,
      "startTime": 1546300800,
      "timeout": 1577836800,
      "since": 999936
    },
```

Re web interface issues: can you setup testnet node and check if there is the same issue after DIP3 activation? Also, I remember @codablock was running it on testnet (not sure if this node is still live) maybe he can share some info.

**Comment by ourlink** [comment]
Ahhh... That might explain it.

We took the following steps to try and resolve the issue;

1. On one node we deleted and re-downloaded the block chain and all supporting files
2. On the 2nd node we just added the ``-reindex`` option to the dashd startup config. 

That did not seem to help at all.

We'll revert these two nodes and see about starting up a node on testnet to test with.

BTW - so is the information on this link considered accurate?  http://178.254.23.111/~pub/Dash/Dash_Info.html 

Can we rely on the chart information to know when DIP3 is implemented?

**Comment by UdjinM6** [comment]
>...
We'll revert these two nodes and see about starting up a node on testnet to test with.

👍 

>BTW - so is the information on this link considered accurate? http://178.254.23.111/~pub/Dash/Dash_Info.html
Can we rely on the chart information to know when DIP3 is implemented?

It's accurate but you can't rely on it because it says nothing about current state of the activation or blocks mined in current window, I would highly recommend to use rpc instead.

**Comment by kr1z1s** [comment]
Works. We can move.

**Comment by ourlink** [comment]
We can close this Issue Ticket as now that DIP003 is active, everything is working as expected.

**Comment by UdjinM6** [comment]
Hmmm... glad that it works but DIP3 is not active yet btw. Anyway, thanks for the info 👍
