### ISSUE TITLE
There is no reward on some block's

### ISSUE THREAD

**Issue by Rem559** [dashpay/p2pool-dash#71]
what's wrong with this block's ?
https://explorer.dash.org/block/00000000000194a8b264c2d9e29e29c936f16b99728e5bcc98da0703324053bd
https://explorer.dash.org/block/0000000000029600aa790f2fcd57e40235232c5ba6f7873429c0deb3165952a9

http://rca-pool.ru/static/
dashd v14.0

Some output's of ~$sudo systemctl status dash
contains an error:
...........
]: return _inlineCallbacks(None, gen, Deferred())
serv2 start.bash[687]: File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
serv2 start.bash[687]: result = g.send(result)
serv2 start.bash[687]: --- ---
serv2 start.bash[687]: File "/home/z/p2pool-dash/p2pool/util/jsonrpc.py", line 68, in handle
serv2 start.bash[687]: id = req.get('id', None)
serv2 start.bash[687]: exceptions.AttributeError: 'list' object has no attribute 'get'
.......

It is difficult to provide the full error code in view of running the pool as a service

**Comment by Rem559** [comment]
+ this:
sudo systemctl status dash
...........
]:     return _inlineCallbacks(None, gen, Deferred())
 serv2 start.bash[687]:   File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
 serv2 start.bash[687]:     result = g.send(result)
 serv2 start.bash[687]: --- <exception caught here> ---
serv2 start.bash[687]:   File "/home/z/p2pool-dash/p2pool/util/jsonrpc.py", line 68, in _handle
serv2 start.bash[687]:     id_ = req.get('id', None)
serv2 start.bash[687]: exceptions.AttributeError: 'list' object has no attribute 'get'
.......

**Comment by UdjinM6** [comment]
Looks like you are mining the wrong chain. Pls make sure to use the latest version of p2pool  i.e 081a7ef

**Comment by Rem559** [comment]
z@serv2:~$ dash-cli -h
Dash Core RPC client version v0.14.0.0

**Comment by UdjinM6** [comment]
I mean the p2pool itself, not the `dashd` - `222f57a-dirty` is outdated.

**Comment by Rem559** [comment]
thanks, i will try to reinstall the pool
